import { createTheme } from "@mui/material/styles";

export const theme = createTheme({
  palette: {
    mode: "light",
    primary: { main: "#4F46E5", dark: "#3730A3", light: "#EEF2FF", contrastText: "#FFFFFF" },
    secondary: { main: "#6366F1", dark: "#4F46E5" },
    success: { main: "#2E7D58" },
    warning: { main: "#B26A16" },
    error: { main: "#B54747" },
    info: { main: "#3B82C4" },
    background: { default: "#F7F7FB", paper: "#FFFFFF" },
    text: { primary: "#202033", secondary: "#6B6B80" },
    divider: "#E4E4EC",
  },
  typography: {
    fontFamily: 'Inter, "Segoe UI", Arial, sans-serif',
    h1: { fontWeight: 800, letterSpacing: "-0.035em" },
    h2: { fontWeight: 800, letterSpacing: "-0.03em" },
    h3: { fontWeight: 750, letterSpacing: "-0.025em" },
    h4: { fontWeight: 750, letterSpacing: "-0.02em" },
    h5: { fontWeight: 700 },
    h6: { fontWeight: 700 },
    body1: { lineHeight: 1.65 },
    body2: { lineHeight: 1.55 },
    button: { fontWeight: 700, textTransform: "none", letterSpacing: 0 },
    overline: { fontWeight: 750, letterSpacing: "0.07em" },
  },
  shape: { borderRadius: 14 },
  components: {
    MuiAppBar: { styleOverrides: { root: { backgroundImage: "none", boxShadow: "0 1px 0 rgba(37, 36, 58, 0.10)" } } },
    MuiButton: {
      defaultProps: { disableElevation: true },
      styleOverrides: { root: { minHeight: 40, borderRadius: 10, paddingInline: 18 }, contained: { boxShadow: "0 4px 12px rgba(79, 70, 229, 0.14)" }, containedPrimary: { "&:hover": { backgroundColor: "#4338CA" } } },
    },
    MuiPaper: { styleOverrides: { root: { backgroundImage: "none" }, outlined: { borderColor: "#E4E4EC" } } },
    MuiCard: { styleOverrides: { root: { backgroundImage: "none", borderColor: "#E4E4EC", boxShadow: "0 3px 14px rgba(32, 32, 51, 0.05)" } } },
    MuiCardContent: { styleOverrides: { root: { padding: 24, "&:last-child": { paddingBottom: 24 } } } },
    MuiTextField: { defaultProps: { variant: "outlined" } },
    MuiOutlinedInput: { styleOverrides: { root: { borderRadius: 11, backgroundColor: "#ffffff" } } },
    MuiFormLabel: { styleOverrides: { asterisk: { color: "#b04444" } } },
    MuiAlert: { styleOverrides: { root: { borderRadius: 11, alignItems: "center" }, standardError: { border: "1px solid #efcccc" }, standardInfo: { border: "1px solid #c9dfe9" }, standardWarning: { border: "1px solid #ead4b5" }, standardSuccess: { border: "1px solid #c5dfd2" } } },
    MuiChip: { styleOverrides: { root: { fontWeight: 700, borderRadius: 8 } } },
    MuiTableHead: { styleOverrides: { root: { backgroundColor: "#F3F3F9" } } },
    MuiTableCell: { styleOverrides: { head: { color: "#45445C", fontWeight: 750 }, root: { borderColor: "#E8E8F0" } } },
    MuiTableRow: { styleOverrides: { root: { "&:nth-of-type(even)": { backgroundColor: "#FBFBFD" }, "&:hover": { backgroundColor: "#F5F4FF" } } } },
    MuiDialogTitle: { styleOverrides: { root: { fontWeight: 750 } } },
  },
});
