import { createTheme } from "@mui/material/styles";

export const theme = createTheme({
  palette: {
    mode: "light",
    primary: { main: "#15536b", dark: "#0c3d50", light: "#4f7f91", contrastText: "#ffffff" },
    secondary: { main: "#2c7565", dark: "#20584d" },
    success: { main: "#2e7358" },
    warning: { main: "#a66418" },
    error: { main: "#b04444" },
    info: { main: "#326b91" },
    background: { default: "#f4f7f8", paper: "#ffffff" },
    text: { primary: "#172b35", secondary: "#5b6b73" },
    divider: "#dce5e9",
  },
  typography: {
    fontFamily: 'Inter, "Segoe UI", Arial, sans-serif',
    h1: { fontWeight: 800, letterSpacing: "-0.035em" },
    h2: { fontWeight: 800, letterSpacing: "-0.03em" },
    h3: { fontWeight: 750, letterSpacing: "-0.025em" },
    h4: { fontWeight: 750, letterSpacing: "-0.02em" },
    h5: { fontWeight: 700 },
    h6: { fontWeight: 700 },
    body1: { lineHeight: 1.65 },
    body2: { lineHeight: 1.55 },
    button: { fontWeight: 700, textTransform: "none", letterSpacing: 0 },
    overline: { fontWeight: 750, letterSpacing: "0.07em" },
  },
  shape: { borderRadius: 14 },
  components: {
    MuiAppBar: { styleOverrides: { root: { backgroundImage: "none", boxShadow: "0 1px 0 rgba(16, 57, 72, 0.14)" } } },
    MuiButton: {
      defaultProps: { disableElevation: true },
      styleOverrides: { root: { minHeight: 40, borderRadius: 10, paddingInline: 18 }, contained: { boxShadow: "0 4px 12px rgba(21, 83, 107, 0.16)" } },
    },
    MuiPaper: { styleOverrides: { root: { backgroundImage: "none" }, outlined: { borderColor: "#dce5e9" } } },
    MuiCard: { styleOverrides: { root: { backgroundImage: "none", borderColor: "#dce5e9", boxShadow: "0 3px 14px rgba(21, 58, 72, 0.055)" } } },
    MuiCardContent: { styleOverrides: { root: { padding: 24, "&:last-child": { paddingBottom: 24 } } } },
    MuiTextField: { defaultProps: { variant: "outlined" } },
    MuiOutlinedInput: { styleOverrides: { root: { borderRadius: 11, backgroundColor: "#ffffff" } } },
    MuiFormLabel: { styleOverrides: { asterisk: { color: "#b04444" } } },
    MuiAlert: { styleOverrides: { root: { borderRadius: 11, alignItems: "center" }, standardError: { border: "1px solid #efcccc" }, standardInfo: { border: "1px solid #c9dfe9" }, standardWarning: { border: "1px solid #ead4b5" }, standardSuccess: { border: "1px solid #c5dfd2" } } },
    MuiChip: { styleOverrides: { root: { fontWeight: 700, borderRadius: 8 } } },
    MuiTableHead: { styleOverrides: { root: { backgroundColor: "#edf3f5" } } },
    MuiTableCell: { styleOverrides: { head: { color: "#34505c", fontWeight: 750 }, root: { borderColor: "#e2e9ec" } } },
    MuiTableRow: { styleOverrides: { root: { "&:nth-of-type(even)": { backgroundColor: "#fafcfc" }, "&:hover": { backgroundColor: "#f1f6f7" } } } },
    MuiDialogTitle: { styleOverrides: { root: { fontWeight: 750 } } },
  },
});
