# Generated by Django 5.2.17 on 2026-08-24 08:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_number',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255)),
                ('stored_name', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=500)),
                ('mime_type', models.CharField(max_length=128)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.application')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attachments',
                'ordering': ('uploaded_at',),
                'indexes': [models.Index(fields=['application', 'uploaded_at'], name='attachments_applica_4a196c_idx')],
            },
        ),
    ]
