# Generated by Django 5.2.17 on 2026-08-24 10:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_application_number_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Активно'), ('COMPLETED', 'Завершено')], db_index=True, default='ACTIVE', max_length=16)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expert_assignments', to='core.application')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_expert_assignments', to=settings.AUTH_USER_MODEL)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expert_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expert_assignments',
                'ordering': ('-assigned_at',),
            },
        ),
        migrations.CreateModel(
            name='ExpertiseReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('comment', models.TextField(blank=True)),
                ('decision', models.CharField(blank=True, choices=[('APPROVED', 'Одобрить'), ('REJECTED', 'Отклонить'), ('REVISION_REQUIRED', 'Вернуть на доработку')], max_length=24)),
                ('draft', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expertise_reports', to='core.application')),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='report', to='core.expertassignment')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expertise_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expertise_reports',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='expertassignment',
            index=models.Index(fields=['expert', 'status'], name='expert_assi_expert__731017_idx'),
        ),
        migrations.AddConstraint(
            model_name='expertassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('application',), name='one_active_expert_assignment_per_application'),
        ),
        migrations.AddConstraint(
            model_name='expertisereport',
            constraint=models.CheckConstraint(condition=models.Q(('score__isnull', True), models.Q(('score__gte', 0), ('score__lte', 100)), _connector='OR'), name='expertise_score_between_0_and_100'),
        ),
    ]
