# Generated by Django 5.2.17 on 2026-08-27 12:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('APPLICATION_SUBMITTED', 'Новая заявка'), ('EXPERT_ASSIGNED', 'Назначение эксперта'), ('REVISION_REQUIRED', 'Требуется доработка'), ('APPLICATION_APPROVED', 'Заявка одобрена'), ('APPLICATION_REJECTED', 'Заявка отклонена'), ('REVISION_SUBMITTED', 'Доработка отправлена')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.application')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='notificatio_recipie_06c470_idx')],
            },
        ),
    ]
